# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Compuguistics
email: do-not@email.me
description: >- # this means to ignore newlines until "baseurl:"
  This is Henry Blanchette's website. The primary topics covered here are: programming languages, computaric logic, mathematics, philosophy, evolution, game theory, game design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "riib11.github.io"
# twitter_username: jekyllrb
github_username: riib11
linkedin_username: henry-blanchette
linkedin_uid: henry-blanchette-520542a1

# Build settings
markdown: kramdown
# theme: minima # removed
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# TODO: sign up for this and put in username
# Disqus
# disqus:
#   shortname: my_disqus_shortname

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
